image: node:10.15.0
pipelines: 
  default: 
    - step: 
        script: 
          - npm ci
          - node dbtest.js
          - npm run test 
        services: 
          - mongo 

definitions: 
  services: 
    mongo: 
      image: mongo