
GET http://localhost:8080/api/designer/event/get
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJrYXNoaXNoIiwicGFzc3dvcmQiOiIiLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDIwLTAzLTE4VDA0OjIzOjA0LjQwNloiLCJ1cGRhdGVkQXQiOiIyMDIwLTAzLTE4VDA0OjIzOjA0LjQwNloiLCJpYXQiOjE1ODU4MDM1NzV9.rQvvFeFdagflnCBi2jDDhT0IjHV1Vgxrn4QGhbTbjTg

###

POST http://139.59.9.25:8080/api/admin
content-type: application/json

{
    "username": "kashish",
    "password": "kashish1",
    "role": "admin"
}

####

POST http://139.59.9.25:8080/api/login
content-type: application/json

{
    "username": "kashish",
    "password": "kashish1"
}

####

POST http://localhost:8080/create-vendor
content-type: application/json

{
    "name": "Preet"
}

####

PUT  http://139.59.9.25:8080/update-vendor/5e8d1acce294d57345f5fa93
content-type: application/json

{
    "address": "New Delhi"
}