# @url = http://localhost:8082/main-server/api/adminapp
@url = https://devbackend.zattire.com/main-server/api/adminapp
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFjMzNiN2RhYWE2MDY1NGQ2NjljOTMiLCJpYXQiOjE2NjY5NTk2NzIsImV4cCI6MTY5ODQ5NTY3Mn0.f5Lz8i5YABOomSPz0ovSrYxrvD_2vWRPu4XHlMiOLG0
@page = page_length=4&page_number=1

# referral ###################################
### by user
get {{url}}/referral/user/5fc48755eae5723192b2c37f?{{page}}
Authorization: Bearer {{token}}

### all
get {{url}}/referral
Authorization: Bearer {{token}}


# user ###################################

### by id
get {{url}}/user/info/60c46e7e847bca741a379b24
Authorization: Bearer {{token}}


### all user
get {{url}}/user
Authorization: Bearer {{token}}


### booking list
get {{url}}/user/booking-list
Authorization: Bearer {{token}}


# brands ################################333
### get brands
get {{url}}/salon/brands
Authorization: Bearer {{token}}

### add brands
post {{url}}/salon/brand
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "brand_name": "Lavish",
    "logo_url": "brand description 3",
    "active": false
} 

### update brands
put {{url}}/salon/brand/63445f0fddb1f24ec5ce89b2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "brand_name": "Lavish",
    "logo_url": "brand description 3",
    "active": true
}

### delete brand
delete {{url}}/salon/brand/63445f0fddb1f24ec5ce89b2
Authorization: Bearer {{token}}

# filter-home ################################333
### get filter-home
get {{url}}/salon/filter-homes
Authorization: Bearer {{token}}

### add filter-home
post {{url}}/salon/filter-home
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "4.0 Rating",
    "type": "RATING",
    "value": "1",
    "priority" : 1
}


### delete filter-home
delete {{url}}/salon/filter-home/63445f0fddb1f24ec5ce89b2
Authorization: Bearer {{token}}



# referral ###################################
### by user
get {{url}}/referral/user/5fc48755eae5723192b2c37f?{{page}}
Authorization: Bearer {{token}}

### all
get {{url}}/referral
Authorization: Bearer {{token}}


# user ###################################

### by id
get {{url}}/user/info/60c46e7e847bca741a379b24
Authorization: Bearer {{token}}


### all user
get {{url}}/user
Authorization: Bearer {{token}}


### booking list
get {{url}}/user/booking-list
Authorization: Bearer {{token}}


# feedback ###################################
### paginated
get {{url}}/feedback?{{page}}
Authorization: Bearer {{token}}

### all
get {{url}}/feedback/all
Authorization: Bearer {{token}}

### rating
get {{url}}/feedback/rating?rating=1
Authorization: Bearer {{token}}

### by booking id
get {{url}}/feedback/booking/5f8386be4b1cb42569c081fd
Authorization: Bearer {{token}}

### by feedback id
get {{url}}/feedback/info/60b74b13f5255500136951de
Authorization: Bearer {{token}}

### update 
put {{url}}/feedback/update/60b74b13f5255500136951de
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "This is a comment"
}

### delete by id
delete {{url}}/feedback/delete/5f8481ffd2d5f54728c4be22
Authorization: Bearer {{token}}


# salon ###################################
get {{url}}/salon/names
Authorization: Bearer {{token}}

# login ###################################
###
post {{url}}/login
Content-Type: application/json

{
    "username" : "mihir",
    "password" : "mihir23"
}
