@url = http://localhost:8082/main-server/api/u
# @url = https://devbackend.zattire.com/main-server/api/u
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzc0ZmZkZDNkMmIyZDAwMTExZDAwOGYiLCJpYXQiOjE2Njg2MTIyMjgsImV4cCI6MTcwMDE0ODIyOH0.sMetVXjYZCNSYbK_lOpMLaOFBQid8Are8xSIXYiCP7I
@page = page_length=4&page_number=1

# user info ######################################################################
get {{url}}/user/info
Authorization: Bearer {{token}}

### favorites
get {{url}}/exploreFavourite/home-page
Authorization: Bearer {{token}}






# booking ######################################################################
### get booking
get {{url}}/booking
Authorization: Bearer {{token}}

# test
### get booking by id
get {{url}}/booking/6376008fcbc213001890bf12
Authorization: Bearer {{token}}






# explore/search/filter ###################
### explore all
get {{url}}/explore/all?page_number=1&page_length=10
Authorization: Bearer {{token}}

### get similar products
get {{url}}/explore/info/624ab068c05bcc001377679d

### search
# get {{url}}/explore/all?service_name=hair
# get {{url}}/explore/all?service_name=hair&start_price=100&end_price=1000
get {{url}}/explore/all?service_name=hair&subarea=Kirti Nagar

### get location
# get {{url}}/location/cities
get {{url}}/location/subarea?city=New Delhi

### service that are recommended
get {{url}}/salon-search?service_name=Bridal HD

# search result - salon list
### if phrase is from static 14 categories then /category
get {{url}}/search/category/?phrase=Hair Coloring

### else /service - complete data
get {{url}}/search/service/?phrase=Hair Botox

### else /service - incomplete data
get {{url}}/search/service/?phrase=Hair do









# feedback ###################################
### paginated
get {{url}}/feedback?{{page}}
Authorization: Bearer {{token}}

### all
get {{url}}/feedback/all
Authorization: Bearer {{token}}

### rating
get {{url}}/feedback/rating?rating=1
Authorization: Bearer {{token}}

### by booking id
get {{url}}/feedback/booking/5f8386be4b1cb42569c081fd
Authorization: Bearer {{token}}

### by feedback id
get {{url}}/feedback/info/60b74b13f5255500136951de
Authorization: Bearer {{token}}

### update 
put {{url}}/feedback/update/60b74b13f5255500136951de
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "This is a comment"
}

### delete by id
delete {{url}}/feedback/delete/5f8481ffd2d5f54728c4be22
Authorization: Bearer {{token}}








# filter ################################
### filters
get {{url}}/salon/filter-home/


### filter-rating
get {{url}}/salon/filter-rating/4

### filter-brand
get {{url}}/salon/filter-brand/Hair Masters

### filter-category
get {{url}}/salon/filter-category/Waxing

### filter-distance
get {{url}}/salon/filter-distance/3.5?latitude=23.8103&longitude=90.4125










# salon ###################################
### adw
get {{url}}/salon/names

### top brands
get {{url}}/salon/top-brands
Authorization: Bearer {{token}}

### popular areas in your state
get {{url}}/salon/popular-areas/New Delhi

### salon by location
get {{url}}/salon/from-subarea/Janakpuri









# login ###################################

post {{url}}/login
Content-Type: application/json

{
    "email" : "mk458978@gmail.com",
    "password" : "123456"
}
